/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw2(GWinApplet appc, GWinData data) { //_CODE_:window1:523778:
  appc.background(230);
} //_CODE_:window1:523778:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.PURPLE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Main Window");
  window1 = new GWindow(this, "GUI Window", 0, 0, 260, 510, false, JAVA2D);
  window1.setActionOnClose(G4P.EXIT_APP);
  window1.addDrawHandler(this, "win_draw2");
  label1 = new GLabel(window1.papplet, 9, 9, 244, 253);
  label1.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label1.setText(" ");
  label1.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label1.setOpaque(false);
  label_deg = new GLabel(window1.papplet, 10, 335, 108, 25);
  label_deg.setText(" ");
  label_deg.setTextBold();
  label_deg.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label_deg.setOpaque(false);
  label_deg_val = new GLabel(window1.papplet, 131, 340, 80, 20);
  label_deg_val.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label_deg_val.setText(" ");
  label_deg_val.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label_deg_val.setOpaque(false);
  label_cur = new GLabel(window1.papplet, 10, 300, 106, 22);
  label_cur.setText("CURVE :");
  label_cur.setTextBold();
  label_cur.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label_cur.setOpaque(false);
  label_cur_val = new GLabel(window1.papplet, 130, 295, 124, 26);
  label_cur_val.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label_cur_val.setText("No Curve Selected");
  label_cur_val.setLocalColorScheme(GCScheme.BLUE_SCHEME);
  label_cur_val.setOpaque(false);
  button_reset = new GButton(window1.papplet, 10, 371, 80, 30);
  button_reset.setText("RESET");
  button_reset.setTextBold();
  label_spc = new GLabel(window1.papplet, 8, 269, 234, 23);
  label_spc.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  label_spc.setText("Press 's' to see special curve function");
  label_spc.setTextBold();
  label_spc.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GLabel label1; 
GLabel label_deg; 
GLabel label_deg_val; 
GLabel label_cur; 
GLabel label_cur_val; 
GButton button_reset; 
GLabel label_spc; 

